# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: review_set.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.review_pb2 as review__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='review_set.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10review_set.proto\x1a\x0creview.proto\"%\n\tReviewSet\x12\x18\n\x07reviews\x18\x01 \x03(\x0b\x32\x07.Reviewb\x06proto3')
  ,
  dependencies=[review__pb2.DESCRIPTOR,])




_REVIEWSET = _descriptor.Descriptor(
  name='ReviewSet',
  full_name='ReviewSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reviews', full_name='ReviewSet.reviews', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=71,
)

_REVIEWSET.fields_by_name['reviews'].message_type = review__pb2._REVIEW
DESCRIPTOR.message_types_by_name['ReviewSet'] = _REVIEWSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReviewSet = _reflection.GeneratedProtocolMessageType('ReviewSet', (_message.Message,), dict(
  DESCRIPTOR = _REVIEWSET,
  __module__ = 'review_set_pb2'
  # @@protoc_insertion_point(class_scope:ReviewSet)
  ))
_sym_db.RegisterMessage(ReviewSet)


# @@protoc_insertion_point(module_scope)
