name: classify
dependencies:
  - python
  - nomkl # prefers the non-mkl version of numpy and pandas, saving ~500mb
  - flask
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pytest
  - protobuf
