version: 2
jobs:
  build_amazoff:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/Amazoff
    steps:
      - checkout
      - npm install
  build_lucas:
    docker:
      - image: circleci/python:3.6.6-jessie-browsers

    working_directory: ~/LUCAS
    steps:
      - checkout
      - run: echo "in LUCAS"
workflows:
  version: 2
  build:
    jobs:
      - build_amazoff
      - build_lucas

