export const TOGGLE_REVIEW = 'TOGGLE_REVIEW';
export const TOGGLE_SINGLE_REVIEW = 'TOGGLE_SINGLE_REVIEW';
export const TOGGLE_SEARCH_REVIEW = 'TOGGLE_SEARCH_REVIEW';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const SET_REVIEWS = 'SET_REVIEWS';
export const SET_BUSINESS = 'SET_BUSINESS';
export const DATASET_WEIGHTS_LOADED = 'DATASET_WEIGHTS_LOADED';
export const SET_REVIEW_WEIGHTS = 'SET_REVIEW_WEIGHTS';
export const SET_FILTERED_REIEWS = 'SET_FILTERED_REIEWS';
export const RESET_FILTERED_REVIEWS = 'RESET_FILTERED_REVIEWS';
export const UPDATE_FILTERED_REVIEWS = 'UPDATE_FILTERED_REVIEWS';

